config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/dashboard' => 'dashboard#index'
  get '/:url_id/delete' => 'dashboard#destroy_shortened'
  post '/' => 'home#shorten'
  root to: 'home#index'
  get '/:id' => 'shortener/shortened_urls#show'

  resources :orders
  resources :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  CURRENCY = 'BDT'
  TAX_PERCENTAGE = 15

  has_and_belongs_to_many :products
  belongs_to :user
  # validate :total_price, :status, :estimated_date, :tracking_id, :confirmation_phone_number, presence: true

  def generate_unique(long_url, user)
    uri = URI.parse(long_url)

    uri = "http://#{uri.to_s}" unless valid? uri
    return if uri.to_s.blank?
    Shortener::ShortenedUrl.generate(uri, owner: user).unique_key unless uri.to_s.blank?
  end

  def calculate_total_price(base_price, weight, tax)
    product_cost(base_price) + cargo_cost(weight) + (tax ? taxes(base_price) : 0)
  end

  def product_cost(base_price)
    rate = currency_conversion_rate(base_price)
    base_price * rate
  end

  def cargo_cost(weight_in_gm)
    # 60tk/100gm
    (weight_in_gm / 100) * 60
  end

  def taxes(base_price)
    (base_price * TAX_PERCENTAGE) / 100
  end

  def currency_conversion_rate(base_price)
    case base_price
      when 1000..4999
        1.45
      when 5000..19999
        1.40
      when 20000..49999
        1.35
      else
        if base_price >= 50000
          1.3
        elsif base_price <= 999
          1.5
        end
    end
  end

  def valid?(uri)
    uri.kind_of?(URI::HTTP) || uri.kind_of?(URI::HTTPS)
  rescue URI::InvalidURIError
    false
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_images

  # validate :url, :quantity, :base_price, :total_price, :shorten_url, presence: true
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  # validate :img_url, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_shortened_urls
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @urls = current_user.shortened_urls
  end

  def destroy_shortened
    @url_id = params[:url_id]
    Shortener::ShortenedUrl.find(@url_id).destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    Rails.logger.info 'Nothing to Do here!'
  end

  def shorten
    long_url = params[:shorten][:url]
    @url = generate_url(long_url)
  end

  def generate_url(param)
    uri = URI.parse(param)

    uri = "http://#{uri.to_s}" unless valid? uri
    unique_key = nil
    unique_key = Shortener::ShortenedUrl.generate(uri, owner: current_user).unique_key unless uri.to_s.blank?
    "#{root_url}#{unique_key}"
  end

  def valid?(uri)
    uri.kind_of?(URI::HTTP) || uri.kind_of?(URI::HTTPS)
  rescue URI::InvalidURIError
    false
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    order = Order.new
    long_url = params[:order][:url]
    unique_key = order.generate_unique(long_url, current_user)
    obj = Crawl::Flipkart::ProductData.new(long_url)
    product_attributes = obj.product_data
    total_price = order.calculate_total_price(product_attributes[:base_price], product_attributes[:weight], false)
    product_attributes.merge!(total_price: total_price, shorten_url: "#{root_url}#{unique_key}")
    @product = Product.create product_attributes.except(:weight, :img_url, :seller_name)
  end

  def create

  end

  def edit

  end

  def update

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end

  def home?
    controller?('home') && action?('index')
  end

  def dashboard?
    controller?('dashboard') && action?('index')
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/dashboard/destroy_shortened.js.erb
$('#url-<%= @url_id %>').fadeOut("slow");

app/views/dashboard/index.html.erb
<div class="container">
  <div class="col-md-12 col-sm-12">
    <table class="table">
      <th>Long URL</th>
      <th>Created</th>
      <th>Short URL</th>
      <th>Clicks</th>
      <th></th>
      <% @urls.each do |url| %>
        <tr id="url-<%= url.id %>">
          <td><%= url.url %></td>
          <td><%= url.created_at.strftime('%b %d, %Y %H:%M:S %p') %></td>
          <td><%= link_to "#{root_url}#{url.unique_key}", "#{root_url}#{url.unique_key}" %></td>
          <td><%= url.use_count %></td>
          <!--Only because of this 'x' icon, otherwise I would use `button_to` and `post` method-->
          <td><%= link_to '<span><i class="fa fa-times"></i></span>'.html_safe, "/#{url.id}/delete", remote: true %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="col-md-12 col-sm-12" id="main-form">
    <% unless user_signed_in? %>
      <%= form_for :shorten, url: '/', method: 'post', remote: true, class: 'form-inline' do |f| %>
        <div class="col-sm-12">
          <%= f.label :url, "<h3>Type your long URL here:</h3>".html_safe %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :url, class: 'form-control' %>
        </div>
        <div class="col-sm-4">
          <%= f.submit 'Shorten', class: 'btn btn-common' %>
        </div>
      <% end %>
    <% else %>
      <%= render partial: 'shared/order_initiation' %>
    <% end %>
  </div>
</div>

app/views/home/shorten.js.erb
$("#shorten_url").val('');
$('#main-form').append("<%= j render partial: 'shared/shorten_created', locals: {url: @url } %>");
$("#myModal").modal("show");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="header">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 overflow">
        </div>
      </div>
    </div>
    <div class="navbar navbar-inverse" role="banner">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <h1>Shortener</h1>
          </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class='<%= 'active' if home? %>'><%= link_to 'Home', root_path %></li>
            <% if user_signed_in? %>
              <li class='<%= 'active' if dashboard? %>'><%= link_to 'Dashboard', dashboard_path %></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </header>
  <%= yield %>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for :orders, class: 'form-inline' do |f| %>
    <div class="col-sm-12">
      <%= f.label :total_price %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :total_price, value: @product.total_price, readonly: true, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= f.label :shipping_address, 'Your Address here: ' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_area :shipping_address, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= f.label :confirmation_phone_number %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :confirmation_phone_number, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= f.label :comment %>
    </div>
    <div class="col-sm-8">
      <%= f.text_area :comment, class: 'form-control' %>
    </div>

    <div class="col-sm-4">
      <%= f.submit 'Confirm', class: 'btn btn-common' %>
    </div>
<% end %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/shared/_order_initiation.html.erb
<%= form_for :order, url: new_order_path, method: 'get', class: 'form-inline' do |f| %>
    <div class="col-sm-12">
      <%= f.label :url, "<h3>Type your Product long URL here:</h3>".html_safe %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= f.submit 'Submit', class: 'btn btn-common' %>
    </div>
<% end %>

app/views/shared/_shorten_created.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h2 class="modal-title" id="myModalLabel">Success!</h2>
      </div>
      <div class="modal-body">
        Here is your shortened url:
        <figure class="highlight">
          <pre>
            <%= link_to "#{url}", url %>
          </pre>
        </figure>
      </div>
    </div>
  </div>
</div>
<script>
  $('#myModal').on('hidden.bs.modal', function () {
    location.reload();
  })
</script>